project_id = "eiilyloldbgnxtrysaky"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322

[studio]
enabled = true
port = 54323

[[fetch-financial-data.functions]]
name = "fetch-financial-data"
verify_jwt = false

[[fetch-financial-data.functions]]
name = "bulk-sync-data"
verify_jwt = false